version: '3.9'
services:
  host1:
    image: dockernet
    environment:
      - DEVICE=host
    networks:
      net1:
        ipv4_address: 10.10.1.2

  host2:
    image: dockernet
    environment:
      - DEVICE=host
    networks:
      net2:
        ipv4_address: 10.10.2.2

  host3:
    image: dockernet
    environment:
      - DEVICE=host
    networks:
      net3:
        ipv4_address: 10.10.3.2

  host4:
    image: dockernet
    environment:
      - DEVICE=host
    networks:
      net10:
        ipv4_address: 10.10.10.2

  host5:
    image: dockernet
    environment:
      - DEVICE=host
    networks:
      net11:
        ipv4_address: 10.10.11.2

  router1:
    image: dockernet
    environment:
      - DEVICE=router
    networks:
      net1:
        ipv4_address: 10.10.1.3
      net6:
        ipv4_address: 10.10.6.3
      net4:
        ipv4_address: 10.10.4.2

  router2:
    image: dockernet
    environment:
      - DEVICE=router
    networks:
      net2:
        ipv4_address: 10.10.2.3
      net4:
        ipv4_address: 10.10.4.3
      net5:
        ipv4_address: 10.10.5.2
      net7:
        ipv4_address: 10.10.7.2

  router3:
    image: dockernet
    environment:
      - DEVICE=router
    networks:
      net3:
        ipv4_address: 10.10.3.3
      net5:
        ipv4_address: 10.10.5.3
      net6:
        ipv4_address: 10.10.6.2
      net9:
        ipv4_address: 10.10.9.2
        
  router4:
    image: dockernet
    environment:
      - DEVICE=router
    networks:
      net7:
        ipv4_address: 10.10.7.3
      net8:
        ipv4_address: 10.10.8.2
      net10:
        ipv4_address: 10.10.10.3
        
  router5:
    image: dockernet
    environment:
      - DEVICE=router
    networks:
      net8:
        ipv4_address: 10.10.8.3
      net9:
        ipv4_address: 10.10.9.3
      net11:
        ipv4_address: 10.10.11.3

networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24
  net2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.2.0/24
  net3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24
  net4:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.4.0/24
  net5:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.5.0/24
  net6:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.6.0/24
  net7:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.7.0/24
  net8:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.8.0/24
  net9:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.9.0/24
  net10:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
  net11:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.11.0/24